'use strict';
const KEY='haejeong-budget-pwa-v1', CATS=[['food','식비','🍴'],['cafe','카페','☕️'],['shopping','쇼핑','👜'],['transport','교통','🚙'],['living','생활','🏠'],['travel','여행','✈️'],['gift','선물','🎁'],['other','기타','💗'],['salary','월급/수입','💵']];
const defaults=()=>({version:1,transactions:[],budget:2000000,categoryBudgets:{},disabled:[],dday:{title:'우리의 기념일',date:''},theme:'pink'});
let data;try{data={...defaults(),...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{data=defaults()}
let tab='welcome',month=new Date().toISOString().slice(0,7),kind='expense',category='food',editing=null,statsMonth=month,calendarDate=today(),entryDate=null;
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>Math.round(Number(n)||0).toLocaleString('ko-KR')+'원';const today=()=>{const d=new Date();return [d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-')};
const save=()=>{try{localStorage.setItem(KEY,JSON.stringify(data));return true}catch{toast('저장 공간 오류: 백업 후 공간을 확보해 주세요');return false}};
const sum=(k,m=month)=>data.transactions.filter(t=>t.kind===k&&t.date.slice(0,7)===m).reduce((s,t)=>s+Number(t.amount),0);
const expenses=()=>data.transactions.filter(t=>t.kind==='expense'&&t.date.slice(0,7)===month);
const catInfo=id=>CATS.find(c=>c[0]===id)||CATS[7];const available=()=>CATS.filter(c=>!data.disabled.includes(c[0]));
const dateLabel=d=>new Date(d+'T12:00:00').toLocaleDateString('ko-KR',{month:'long',day:'numeric',weekday:'short'});
function toast(msg){document.querySelector('.toast')?.remove();let x=document.createElement('div');x.className='toast';x.textContent=msg;document.body.append(x);setTimeout(()=>x.remove(),2700)}
const header=(title,extra='')=>`<header class="top"><h1>${title}</h1>${extra}</header>`;
const nav=()=>`<nav class="tabbar" aria-label="하단 메뉴">${[['home','⌂','홈'],['history','▤','내역'],['add','+','등록'],['stats','◉','통계'],['settings','⚙','설정']].map(([id,icon,name])=>id==='add'?`<button class="plus" data-go="add" aria-label="거래 등록">+</button>`:`<button class="tab ${tab===id?'on':''}" data-go="${id}"><b>${icon}</b>${name}</button>`).join('')}</nav>`;
function welcome(){return `<div class="welcome"><div class="hello">HELLO, 해정이! ❤️</div><div class="heart">♥　♥</div><img src="assets/kitty.png" alt="하트를 든 키티"><h1>해정이<br>가계부 ❤️</h1><div style="font-size:17px;color:#ad5c7b">오늘도 행복한 하루</div><div class="heart">❤️</div><button class="primary" data-go="home">시작하기</button><div class="footer">With Love, 승림이가 ❤️</div></div>`}
function ddayText(){if(!data.dday?.date)return '날짜를 설정해 주세요';const a=new Date(today()+'T12:00:00'),b=new Date(data.dday.date+'T12:00:00');const diff=Math.round((b-a)/86400000);return diff===0?'D-Day':diff>0?'D-'+diff:'D+'+(-diff)}
function home(){const inc=sum('income'),out=sum('expense'),remaining=data.budget-out,pct=data.budget>0?Math.min(100,Math.max(0,out/data.budget*100)):0;return `${header('해정이 가계부 ❤️',`<img class="kitty" src="assets/kitty.png" alt="키티">`)}<div class="row"><button class="secondary" id="prevMonth">‹</button><strong>${month.replace('-','년 ')}월</strong><button class="secondary" id="nextMonth">›</button></div><section class="card pink"><div class="muted">이번 달 남은 예산</div><div class="balance">${money(remaining)}</div><div class="row"><small>사용 ${money(out)}</small><small>예산 ${money(data.budget)}</small></div><div class="progress" style="background:#ffffff66"><i style="width:${pct}%;background:#fff"></i></div></section><div class="three"><div class="mini">수입<strong class="income">${money(inc)}</strong></div><div class="mini">지출<strong class="expense">${money(out)}</strong></div><div class="mini">잔액<strong>${money(inc-out)}</strong></div></div><div class="section"><h2>❤️ 우리의 D-Day</h2><button class="secondary" data-go="dday">설정</button></div><div class="card row" data-go="dday" role="button" tabindex="0"><div><strong>${esc(data.dday.title)}</strong><div class="muted">${data.dday.date||'날짜 미설정'}</div></div><strong style="font-size:23px;color:#ef4389">${ddayText()}</strong></div><div class="section"><h2>📅 달력 가계부</h2><button class="secondary" data-go="calendar">달력 보기 ›</button></div><button class="card calendar-preview" data-go="calendar">날짜별 수입·지출을 달력에서 확인해요 ❤️ <span>📅</span></button><div class="section"><h2>카테고리</h2><button class="secondary" data-go="categories">관리</button></div><div class="grid">${available().filter(c=>c[0]!=='salary').map(c=>`<button class="cat" data-category="${c[0]}"><span>${c[2]}</span>${c[1]}</button>`).join('')}</div><div class="section"><h2>최근 내역</h2><button class="secondary" data-go="history">전체 보기</button></div><div class="card">${transactionRows(data.transactions.filter(t=>t.date.slice(0,7)===month).sort((a,b)=>b.date.localeCompare(a.date)).slice(0,4))}</div>`}
function transactionRows(items){return items.length?items.map(t=>`<div class="row line"><div><strong>${catInfo(t.category)[2]} ${esc(catInfo(t.category)[1])}</strong><div class="muted">${esc(t.date)} · ${esc(t.memo||'메모 없음')}</div></div><div class="right"><div class="amount ${t.kind==='expense'?'expense':'income'}">${t.kind==='expense'?'-':'+'}${money(t.amount)}</div><button class="secondary" data-edit="${esc(t.id)}" style="margin-top:5px;padding:5px 9px;font-size:12px">수정</button></div></div>`).join(''):'<div class="empty">아직 기록이 없어요 ❤️</div>'}
function history(){let items=data.transactions.filter(t=>t.date.slice(0,7)===month).sort((a,b)=>b.date.localeCompare(a.date));let dates=[...new Set(items.map(t=>t.date))];return `${header('내역 ❤️',`<button class="secondary" data-go="calendar">📅 달력</button>`)}<div class="row"><button class="secondary" id="prevMonth">‹</button><strong>${month.replace('-','년 ')}월</strong><button class="secondary" id="nextMonth">›</button></div><div class="card row"><span>수입 <b class="income">${money(sum('income'))}</b></span><span>지출 <b class="expense">${money(sum('expense'))}</b></span></div>${dates.length?dates.map(d=>`<div class="section"><h2>${dateLabel(d)}</h2></div><div class="card">${transactionRows(items.filter(t=>t.date===d))}</div>`).join(''):'<div class="card empty">이 달의 내역이 없어요.</div>'}`}
function calendar(){
 const [year,mon]=month.split('-').map(Number),first=new Date(year,mon-1,1).getDay(),days=new Date(year,mon,0).getDate();
 const records=data.transactions.filter(t=>t.date.slice(0,7)===month);
 if(!calendarDate.startsWith(month)||Number(calendarDate.slice(8))>days)calendarDate=month+'-01';
 const selected=records.filter(t=>t.date===calendarDate).sort((a,b)=>a.kind.localeCompare(b.kind));
 const totals=records.reduce((map,t)=>{let x=map[t.date]||(map[t.date]={income:0,expense:0});x[t.kind]+=Number(t.amount);return map},{});
 const cells=Array.from({length:first},()=>'<span class="calendar-blank" aria-hidden="true"></span>');
 for(let day=1;day<=days;day++){
   const date=month+'-'+String(day).padStart(2,'0'),v=totals[date],active=date===calendarDate;
   cells.push(`<button type="button" class="calendar-day ${active?'selected':''} ${date===today()?'today':''}" data-caldate="${date}" aria-label="${date} ${v?'수입 '+money(v.income)+' 지출 '+money(v.expense):'내역 없음'}" aria-pressed="${active}"><span class="day-num">${day}</span>${v?`<span class="day-expense">${v.expense?'-'+compactMoney(v.expense):''}</span><span class="day-income">${v.income?'+'+compactMoney(v.income):''}</span>`:'<span class="day-empty"></span>'}</button>`);
 }
 const income=selected.filter(t=>t.kind==='income').reduce((a,t)=>a+Number(t.amount),0),expense=selected.filter(t=>t.kind==='expense').reduce((a,t)=>a+Number(t.amount),0);
 return `${header('달력 가계부 ❤️',`<button class="secondary" data-go="history">목록 보기</button>`)}<section class="card"><div class="row calendar-month"><button class="secondary" id="prevMonth" aria-label="이전 달">‹</button><strong>${year}년 ${mon}월</strong><button class="secondary" id="nextMonth" aria-label="다음 달">›</button></div><div class="calendar-grid calendar-weekdays">${['일','월','화','수','목','금','토'].map(x=>`<span>${x}</span>`).join('')}</div><div class="calendar-grid calendar-days">${cells.join('')}</div><div class="calendar-legend"><span class="expense">● 지출</span><span class="income">● 수입</span></div></section><div class="section"><h2>${dateLabel(calendarDate)} 내역</h2><button class="secondary" id="calendarAdd">+ 이 날짜에 등록</button></div><div class="card"><div class="row calendar-summary"><span>수입 <b class="income">${money(income)}</b></span><span>지출 <b class="expense">${money(expense)}</b></span></div>${transactionRows(selected)}</div>`;
}
const compactMoney=n=>Math.round(Number(n)).toLocaleString('ko-KR');
function add(){let t=editing?data.transactions.find(x=>x.id===editing):null;let active=kind==='income'?available().filter(c=>['salary','gift','other'].includes(c[0])):available().filter(c=>c[0]!=='salary');if(!active.some(c=>c[0]===category))category=active[0]?.[0]||'other';return `${header(t?'내역 수정 ❤️':'지출/수입 등록 ❤️',`<img class="kitty" src="assets/kitty.png" alt="키티">`)}<div class="card"><div class="segment"><button data-kind="expense" class="${kind==='expense'?'selected':''}">지출</button><button data-kind="income" class="${kind==='income'?'selected':''}">수입</button></div><form id="transactionForm"><label class="field" for="amount">금액</label><input class="control" id="amount" name="amount" type="number" min="1" max="999999999999" step="1" inputmode="numeric" required placeholder="0" value="${t?t.amount:''}"><div class="field">카테고리</div><div class="grid" style="grid-template-columns:repeat(3,1fr)">${active.map(c=>`<button type="button" class="cat ${category===c[0]?'active':''}" data-pick="${c[0]}"><span>${c[2]}</span>${c[1]}</button>`).join('')}</div><label class="field" for="date">날짜</label><input class="control" id="date" name="date" type="date" required value="${t?t.date:(entryDate||today())}"><label class="field" for="memo">메모</label><textarea class="control" id="memo" name="memo" maxlength="200" rows="3" placeholder="어디에 사용했나요?">${t?esc(t.memo):''}</textarea><button class="primary" type="submit">${t?'수정 저장':'저장하기 ❤️'}</button>${t?'<button class="secondary" type="button" id="deleteTransaction" style="width:100%;margin-top:10px">이 내역 삭제</button>':''}</form></div>`}
function stats(){const totals=CATS.map(c=>({c,value:expenses().filter(t=>t.category===c[0]).reduce((s,t)=>s+Number(t.amount),0)})).filter(x=>x.value>0).sort((a,b)=>b.value-a.value);let total=sum('expense'),colors=['#f05292','#ffadbe','#f8c66a','#9a84d5','#70b9ab','#fa8a79','#a2b8eb','#b98db1','#9eaf8c'],start=0;let stops=totals.map((x,i)=>{let a=start;start+=x.value/total*100;return `${colors[i%colors.length]} ${a}% ${start}%`}).join(',');return `${header('통계 ❤️')}<div class="card"><div class="row"><strong>${month.replace('-','년 ')}월 지출</strong><strong class="expense">${money(total)}</strong></div>${total?`<div class="donut" style="background:conic-gradient(${stops})"><div class="donut-inner">이번 달<br>${money(total)}</div></div>${totals.map((x,i)=>`<div class="line"><div class="row"><span><span style="color:${colors[i%colors.length]}">●</span> ${x.c[2]} ${x.c[1]}</span><strong>${Math.round(x.value/total*100)}%</strong></div><div class="row muted"><span>${money(x.value)}</span></div><div class="progress"><i style="width:${x.value/total*100}%;background:${colors[i%colors.length]}"></i></div></div>`).join('')}`:'<div class="empty">지출을 등록하면 통계가 표시돼요.</div>'}</div>`}
function budget(){return `${header('예산 관리 ❤️')}<div class="card"><form id="budgetForm"><label class="field" for="budget">월 예산 (원)</label><input class="control" id="budget" type="number" min="0" step="1" required value="${data.budget}"><button class="primary">월 예산 저장</button></form></div><div class="section"><h2>카테고리별 지출</h2></div><div class="card">${CATS.filter(c=>c[0]!=='salary').map(c=>{let spent=expenses().filter(t=>t.category===c[0]).reduce((s,t)=>s+Number(t.amount),0),limit=Number(data.categoryBudgets[c[0]]||0);return `<div class="line"><div class="row"><strong>${c[2]} ${c[1]}</strong><span>${money(spent)}</span></div><div class="row muted"><span>카테고리 예산</span><input type="number" data-catbudget="${c[0]}" min="0" step="1" value="${limit}" style="width:110px;border:1px solid #ffd1e1;border-radius:8px;padding:5px;text-align:right" aria-label="${c[1]} 예산"></div><div class="progress"><i style="width:${limit?Math.min(100,spent/limit*100):0}%"></i></div></div>`}).join('')}<button class="primary" id="saveCatBudgets">카테고리 예산 저장</button></div>`}
function dday(){return `${header('D-Day 설정 ❤️')}<div class="card"><form id="ddayForm"><label class="field" for="ddtitle">기념일 이름</label><input class="control" id="ddtitle" maxlength="40" required value="${esc(data.dday.title)}"><label class="field" for="dddate">기념일 날짜</label><input class="control" id="dddate" type="date" required value="${esc(data.dday.date)}"><div class="card" style="text-align:center;background:#fff2f7"><strong>${ddayText()}</strong></div><button class="primary">D-Day 저장</button><button type="button" class="secondary" id="clearDday" style="width:100%;margin-top:10px">D-Day 삭제</button></form></div>`}
function categories(){return `${header('카테고리 관리 ❤️')}<div class="card"><p class="muted">끄면 홈과 거래 등록 화면에서 숨겨져요. 기존 기록은 삭제되지 않아요.</p>${CATS.map(c=>`<label class="row line"><span>${c[2]} ${c[1]}</span><input type="checkbox" data-togglecat="${c[0]}" ${!data.disabled.includes(c[0])?'checked':''}></label>`).join('')}</div>`}
function backup(){return `${header('백업 / 복원 ❤️')}<div class="card"><h2>데이터 백업</h2><p class="muted">가계부 기록·예산·D-Day를 JSON 파일로 내려받아요.</p><button class="primary" id="export">백업 파일 다운로드</button><button class="secondary" id="copyBackup" style="width:100%;margin-top:10px">백업 내용 복사</button></div><div class="card"><h2>데이터 복원</h2><p class="warn">복원하면 현재 기록이 백업 내용으로 교체됩니다. 먼저 현재 데이터를 백업해 주세요.</p><label class="field" for="restoreFile">JSON 백업 파일 선택</label><input class="control" id="restoreFile" type="file" accept=".json,application/json"><label class="field" for="restoreText">또는 JSON 붙여넣기</label><textarea class="control" id="restoreText" rows="4" placeholder="백업 JSON 붙여넣기"></textarea><button class="primary" id="restore">백업 복원</button></div>`}
function settings(){return `${header('설정 ❤️')}<div class="card row"><img src="assets/avatar.png" style="width:65px;height:65px;object-fit:contain" alt="키티 프로필"><div style="flex:1"><strong>해정이의 가계부 ❤️</strong><div class="muted">승림이가 만들었어</div></div></div><div class="card">${[['categories','카테고리 관리','🍴'],['budget','예산 설정','💰'],['dday','D-Day 설정','❤️'],['backup','데이터 백업 / 복원','📦'],['theme','테마 설정','🎀'],['about','앱 정보','ℹ️']].map(([id,label,icon])=>`<button class="row line" data-go="${id}" style="border:0;background:none;width:100%;text-align:left;color:inherit"><span>${icon} ${label}</span><span>›</span></button>`).join('')}</div><p class="warn">기록은 이 기기의 브라우저 저장소에 보관됩니다. Safari 데이터 삭제·기기 변경에 대비해 정기적으로 JSON 백업을 저장하세요.</p>`}
function render(){const pages={welcome,home,history,calendar,add,stats,budget,dday,categories,backup,settings,theme:()=>`${header('테마 설정 ❤️')}<div class="card">🎀 핑크 키티 테마가 적용되어 있어요.</div>`,about:()=>`${header('앱 정보 ❤️')}<div class="card"><h2>해정이 가계부 ❤️</h2><p>승림이가 해정이를 위해 만든 가계부 웹앱</p><p class="muted">PWA v1.1 · 기기 내 저장 · 오프라인 사용 지원</p></div>`};$('#app').innerHTML=`<main class="shell">${(pages[tab]||welcome)()}</main>${tab==='welcome'?'':nav()}`;}
function go(id){if(id==='add'){editing=null;kind='expense';category='food';entryDate=null}if(id==='calendar'&&!calendarDate.startsWith(month))calendarDate=month+'-01';tab=id;render();window.scrollTo(0,0)}
document.addEventListener('click',async e=>{let b=e.target.closest('[data-go]');if(b){go(b.dataset.go);return}let day=e.target.closest('[data-caldate]');if(day){calendarDate=day.dataset.caldate;render();return}if(e.target.id==='calendarAdd'){editing=null;kind='expense';category='food';entryDate=calendarDate;tab='add';render();return}let c=e.target.closest('[data-category]');if(c){editing=null;entryDate=null;kind='expense';category=c.dataset.category;tab='add';render();return}let p=e.target.closest('[data-pick]');if(p){category=p.dataset.pick;render();return}let k=e.target.closest('[data-kind]');if(k){kind=k.dataset.kind;category=kind==='income'?'salary':'food';render();return}let ed=e.target.closest('[data-edit]');if(ed){let t=data.transactions.find(t=>t.id===ed.dataset.edit);if(t){editing=t.id;kind=t.kind;category=t.category;tab='add';render()}return}if(e.target.id==='prevMonth'||e.target.id==='nextMonth'){let [y,m]=month.split('-').map(Number),d=new Date(y,m-1+(e.target.id==='prevMonth'?-1:1),1);month=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`;if(tab==='calendar')calendarDate=month+'-01';render()}if(e.target.id==='deleteTransaction'&&editing&&confirm('이 내역을 삭제할까요?')){data.transactions=data.transactions.filter(t=>t.id!==editing);save();editing=null;go(tab==='calendar'?'calendar':'history')}if(e.target.id==='clearDday'&&confirm('D-Day를 삭제할까요?')){data.dday={title:'우리의 기념일',date:''};save();render()}if(e.target.id==='saveCatBudgets'){document.querySelectorAll('[data-catbudget]').forEach(el=>data.categoryBudgets[el.dataset.catbudget]=Math.max(0,Math.round(Number(el.value)||0)));save();toast('카테고리 예산 저장 완료');render()}if(e.target.id==='export'){const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`해정이_가계부_백업_${today()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}if(e.target.id==='copyBackup'){try{await navigator.clipboard.writeText(JSON.stringify(data,null,2));toast('백업 내용을 복사했어요')}catch{toast('복사 실패: 파일 다운로드를 이용해 주세요')}}if(e.target.id==='restore'){let text=$('#restoreText').value,file=$('#restoreFile').files[0];if(!text&&file)text=await file.text();try{let obj=JSON.parse(text);if(!validate(obj))throw Error('잘못된 형식');if(!confirm('현재 데이터를 백업 데이터로 교체할까요?'))return;data={...defaults(),...obj};save();toast('복원 완료');go('home')}catch{toast('올바른 가계부 JSON 파일이 아니에요')}}});
document.addEventListener('change',e=>{if(e.target.matches('[data-togglecat]')){let id=e.target.dataset.togglecat;if(e.target.checked)data.disabled=data.disabled.filter(x=>x!==id);else if(available().length<=1){e.target.checked=true;toast('카테고리는 하나 이상 필요해요');return}else data.disabled=[...new Set([...data.disabled,id])];save()}});
document.addEventListener('submit',e=>{e.preventDefault();if(e.target.id==='transactionForm'){let amount=Number($('#amount').value),date=$('#date').value,memo=$('#memo').value.trim();if(!Number.isSafeInteger(amount)||amount<=0||amount>999999999999||!/^\d{4}-\d{2}-\d{2}$/.test(date)){toast('금액과 날짜를 확인해 주세요');return}let t={id:editing||crypto.randomUUID(),date,kind,category,amount,memo};if(editing)data.transactions=data.transactions.map(x=>x.id===editing?t:x);else data.transactions.push(t);save();editing=null;entryDate=null;month=date.slice(0,7);calendarDate=date;toast('저장했어요 ❤️');go('calendar')}if(e.target.id==='budgetForm'){data.budget=Math.max(0,Math.round(Number($('#budget').value)||0));save();toast('월 예산 저장 완료');go('home')}if(e.target.id==='ddayForm'){data.dday={title:$('#ddtitle').value.trim(),date:$('#dddate').value};save();toast('D-Day 저장 완료');go('home')}});
function validate(o){return o&&typeof o==='object'&&!Array.isArray(o)&&Array.isArray(o.transactions)&&o.transactions.length<100000&&o.transactions.every(t=>t&&typeof t.id==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(t.date)&&['income','expense'].includes(t.kind)&&CATS.some(c=>c[0]===t.category)&&Number.isSafeInteger(Number(t.amount))&&Number(t.amount)>0&&typeof t.memo==='string')&&Number.isFinite(Number(o.budget))&&Number(o.budget)>=0&&(!o.dday||typeof o.dday.title==='string'&&typeof o.dday.date==='string')};
render();if('serviceWorker'in navigator&&location.protocol==='https:')navigator.serviceWorker.register('./sw.js').catch(()=>{});
